# usage: https://github.com/sagiegurari/cargo-make


[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

##############

[tasks.openocd]
command = "openocd"
args = [
    "-f",
    "openocd.cfg",
]

##############

[tasks.f]
command = "arm-none-eabi-gdb"
args = ["-x", "flash.gdb"]
dependencies = ["build"]

[tasks.callgraph]
dependencies = ["build"]
script_runner = "@shell"
script = '''
./gen-callgraph.py --toolprefix arm-none-eabi- --call_cmd b ${executable} | dot -v -Tsvg -o/tmp/callgraph.svg
xdg-open /tmp/callgraph.svg
'''